#!/usr/bin/env python3
"""Build browser-safe viewing copies and posters, preserving all originals.
Usage: python3 tools/prepare_media.py --ffmpeg /path/to/ffmpeg --ffprobe /path/to/ffprobe
"""
import argparse, json, pathlib, subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
# Titles describe the supplied files; no client relationships or commissions are implied.
PROJECTS = [
 ('Bullet Train trailer.mp4', 'bullet-train', 'Bullet Train', 'Video Editing', 'Trailer edit', 'cinema', .75),
 ('nabtaCode_ad12.mp4', 'nabta-12', 'NabtaCode / 12', 'Social Content', 'Social ad', 'portrait', .55),
 ('lisaReel_02.mp4', 'lisa-reel', 'Lisa / Reel 02', 'Video Editing', 'Short-form edit', 'portrait', .35),
 ('nabtaCode_ad03.mp4', 'nabta-03', 'NabtaCode / 03', 'Social Content', 'Social ad', 'portrait', .15),
 ('nabtaCode_ad10.mp4', 'nabta-10', 'NabtaCode / 10', 'Social Content', 'Social ad', 'portrait', .35),
 ('nabtaCode_ad09.mp4', 'nabta-09', 'NabtaCode / 09', 'Social Content', 'Social ad', 'portrait', .55),
 ('transition fyp.mp4', 'transition-edit', 'A change of scene', 'Video Editing', 'Transition edit', 'portrait', .15),
 ('Ali Othman Productions animation.mp4', 'ali-productions', 'Ali Othman Productions', 'Motion Graphics', 'Identity animation', 'motion', .55),
 ('Xylon Intro.mp4', 'xylon-intro', 'Xylon / Intro', 'Motion Graphics', 'Logo animation', 'motion', .75),
 ('Xylon Outro.mov', 'xylon-outro', 'Xylon / Outro', 'Motion Graphics', 'End screen', 'motion', .35),
 ('tedx speaker name animation.mp4', 'speaker-title', 'TEDx / Speaker title', 'Motion Graphics', 'Lower-third animation', 'motion', .55),
 ('Follow Animation.mov', 'follow', 'Follow / Animation', 'Motion Graphics', 'Social overlay', 'motion', .55),
 ('Subscribe Animation.mov', 'subscribe', 'Subscribe / Animation', 'Motion Graphics', 'Social overlay', 'motion', .55),
 ('Transetion.avi', 'graphic-transition', 'The graphic transition', 'Motion Graphics', 'Animated transition', 'motion', .15),
]

def run(cmd):
 subprocess.run(cmd, check=True)

def main():
 parser=argparse.ArgumentParser();parser.add_argument('--ffmpeg',default='ffmpeg');parser.add_argument('--ffprobe',default='ffprobe');args=parser.parse_args()
 for directory in ['media','posters']: (ROOT/'assets'/directory).mkdir(exist_ok=True)
 actual={p.name for p in (ROOT/'assets/videos').iterdir() if p.is_file()}
 expected={p[0] for p in PROJECTS}
 if actual != expected: raise SystemExit(f'Update PROJECTS for these files: {actual ^ expected}')
 manifest=[]
 for filename,slug,title,category,label,group,fraction in PROJECTS:
  source=ROOT/'assets/videos'/filename
  info=json.loads(subprocess.check_output([args.ffprobe,'-v','error','-show_streams','-show_format','-of','json',str(source)]))
  stream=next(s for s in info['streams'] if s['codec_type']=='video');duration=float(info['format']['duration'])
  w,h=stream['width'],stream['height'];alpha=stream['pix_fmt'] in ('argb','bgra','rgba','yuva420p')
  dst=ROOT/'assets/media'/f'{slug}.mp4';poster=ROOT/'assets/posters'/f'{slug}.webp'
  scale="scale=w='min(iw,1600)':h='min(ih,1600)':force_original_aspect_ratio=decrease:force_divisible_by=2,setsar=1"
  existing = subprocess.run([args.ffprobe, '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', str(dst)], capture_output=True, text=True) if dst.exists() else None
  valid = existing is not None and existing.returncode == 0 and abs(float(existing.stdout.strip() or '0') - duration) < .25
  if not valid:
   cmd=[args.ffmpeg,'-v','error','-y','-i',str(source)]
   if alpha:
    cmd += ['-f','lavfi','-i',f'color=c=0x070607:s={w}x{h}:r=30','-filter_complex',f'[1:v][0:v]overlay=shortest=1,{scale}[out]','-map','[out]','-map','0:a?']
   else: cmd += ['-map','0:v:0','-map','0:a?','-vf',scale]
   cmd += ['-c:v','libx264','-preset','fast','-crf','23','-pix_fmt','yuv420p','-threads','4','-c:a','aac','-b:a','128k','-movflags','+faststart',str(dst)]
   print(f'Preparing {filename}',flush=True);run(cmd)
  if not poster.exists():
   run([args.ffmpeg,'-v','error','-y','-ss',str(duration*fraction),'-i',str(dst),'-frames:v','1','-vf','scale=1200:1200:force_original_aspect_ratio=decrease','-c:v','libwebp','-quality','85','-threads','2',str(poster)])
  playback=json.loads(subprocess.check_output([args.ffprobe,'-v','error','-select_streams','v:0','-show_streams','-of','json',str(dst)]))['streams'][0]
  manifest.append(dict(id=slug,title=title,category=category,label=label,group=group,source=f'assets/media/{slug}.mp4',original=f'assets/videos/{filename}',poster=f'assets/posters/{slug}.webp',width=playback['width'],height=playback['height'],duration=round(duration,2),hasAudio=any(s['codec_type']=='audio' for s in info['streams'])))
 (ROOT/'assets/projects.js').write_text('// Generated by tools/prepare_media.py.\nexport const projects = '+json.dumps(manifest,indent=2)+';\n')
 from render_gallery import render_gallery
 render_gallery(manifest)
 print(f'Ready: {len(manifest)} videos',flush=True)

if __name__=='__main__': main()
